/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as hydroCredTokenSol from "./HydroCredToken.sol";
export type { hydroCredTokenSol };
import type * as marketplaceSol from "./Marketplace.sol";
export type { marketplaceSol };
export type { RoleManager } from "./RoleManager";
