/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HydroCredToken__factory } from "./HydroCredToken__factory";
export { IRoleManager__factory } from "./IRoleManager__factory";
