/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHydroCredToken,
  IHydroCredTokenInterface,
} from "../../../contracts/Marketplace.sol/IHydroCredToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHydroCredToken__factory {
  static readonly abi = _abi;
  static createInterface(): IHydroCredTokenInterface {
    return new Interface(_abi) as IHydroCredTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHydroCredToken {
    return new Contract(address, _abi, runner) as unknown as IHydroCredToken;
  }
}
