/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRoleManager2,
  IRoleManager2Interface,
} from "../../../contracts/Marketplace.sol/IRoleManager2";

const _abi = [
  {
    inputs: [],
    name: "PRODUCER_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRoleManager2__factory {
  static readonly abi = _abi;
  static createInterface(): IRoleManager2Interface {
    return new Interface(_abi) as IRoleManager2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRoleManager2 {
    return new Contract(address, _abi, runner) as unknown as IRoleManager2;
  }
}
