/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IHydroCredToken } from "./IHydroCredToken";
export type { IRoleManager2 } from "./IRoleManager2";
export type { Marketplace } from "./Marketplace";
